### ISSUE TITLE
Use single-width glyphs

### ISSUE THREAD

**Issue by blueyed** [ryanoasis/vim-webdevicons#11]
All (or at least) most glyphs appear to be wider than the normal characters (double width), and therefore an additional space gets appended.

Unfortunately the URxvt terminal does not handle those like gVim or libvte-based terminals (e.g. gnome-terminal) do ([ref](http://lists.schmorp.de/pipermail/rxvt-unicode/2014q4/002043.html)).

Would it be possible to only use a single character cell (as wide as a `M` then probably)?

**Comment by ryanoasis** [comment]
WIP: https://cloud.githubusercontent.com/assets/8083459/6205330/63451b90-b538-11e4-9b5e-11f4d5c3afc8.png

**Comment by ryanoasis** [comment]
For reference and linking ryanoasis/nerd-filetype-glyphs-fonts-patcher#4

**Comment by ryanoasis** [comment]
working now as of:
* ryanoasis/nerd-filetype-glyphs-fonts-patcher@6c6ef8ef0ca382efbd39bd709007e6ee8f64edbf
 * with mono spaced cli flag
  * e.g. `./font-patcher unpatched-sample-fonts/Droid\ Sans\ Mono\ for\ Powerline.otf --use-single-width-glyphs --quiet`
* 4aa25340e9a7ebb35fced84598f85158767c71db
 * with g:WebDevIconsUnicodeGlyphDoubleWidth flag settings, `let g:WebDevIconsUnicodeGlyphDoubleWidth = 0`
