### ISSUE TITLE
Add support (patch) for PragmataPro for Powerline

### ISSUE THREAD

**Issue by DemonCloud** [ryanoasis/vim-webdevicons#15]
I find Some best Program Fonts in here

https://github.com/Trazyn/Powerline-font

You mind this?  ：）

**Comment by ryanoasis** [comment]
@DemonCloud your requested font is now available here: https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher/tree/master/patched-fonts

unless you have any issues with that I am going to close this ticket :smile_cat:

**Comment by ryanoasis** [comment]
![selection_035](https://cloud.githubusercontent.com/assets/8083459/5849189/e61b8cda-a1af-11e4-8e51-0a64ea65cbf3.png)

**Comment by DemonCloud** [comment]
WOW!! good work!
