### ISSUE TITLE
add support for directory glyphs (and configurable)

### ISSUE THREAD

**Issue by aliev** [ryanoasis/vim-webdevicons#22]
Can you add something like that? https://dl.dropboxusercontent.com/u/5837324/vim-nerdtree.png (directory icons). I use a patched nerdtree

**Comment by ryanoasis** [comment]
@aliev Yes that is definitely possible. I believe right now I just ignore folders. I will see if I can get something in for this on next release unless you want to try it yourself.

**Comment by aliev** [comment]
@ryanoasis thank you!
