### ISSUE TITLE
getting errors after updating webdevicons and airline

### ISSUE THREAD

**Issue by aliev** [ryanoasis/vim-webdevicons#23]
getting errors after updating webdevicons and airline: https://dl.dropboxusercontent.com/u/5837324/errors.png

**Comment by aliev** [comment]
@ryanoasis i think this is a reason https://github.com/bling/vim-airline/commit/ca925efdbfe88b03597efc7caee4ee8762a2cfe0

**Comment by aliev** [comment]
@ryanoasis was created pull request https://github.com/ryanoasis/vim-webdevicons/pull/24

**Comment by ryanoasis** [comment]
Wow that would definitely break it yeah. Thanks for the fix. I'll try to get to this soon, at least you have the fix for those who cannot wait :smile: :+1:

**Comment by aliev** [comment]
@ryanoasis Thank you too :)

**Comment by ryanoasis** [comment]
related pull request #24 has been merged in. closing this.
