### ISSUE TITLE
Remove [ ] wrapping icons.

### ISSUE THREAD

**Issue by jordwalke** [ryanoasis/vim-webdevicons#27]
Is it possible to remove the wrapping [ ] around the icons in the NERDTree? I think it would look cleaner without them.

**Comment by ryanoasis** [comment]
Heh I actually messed around with some test code to do this a while ago but it broke some big things

So yes this is something I would like to improve, either directly or a PR on NERDTree (but that would be difficult to get one in I think)

**Comment by jordwalke** [comment]
You can always fork nerd tree and have people point Vundle to your fork if people want to avoid the extra [] characters.

**Comment by ryanoasis** [comment]
That is true but my test code was essentially a fork of a specific part of code that displays the brackets. I think this is the one I was messing with:

let g:NERDTreeFlagSet.renderToString = substitute(g:NERDTreeFlagSet.renderToString(), "[", "x", "")

**Comment by jordwalke** [comment]
I just realized something - wouldn't there be a way to use the `vim` `conceal` capabilities? You could add a concealment for each `GLYPH` such as: `[GLYPH] => GLYPH`.
You would probably need to have `concealcursor=nvc` for it to look good, and that's okay except it would conflict with the very small set of people that wish to use `concealcursor` for other purposes with a setting different than `nvc`. If they use `nvc`, it should be fine.

**Comment by ryanoasis** [comment]
That is an interesting idea! Thanks I'll have to try it!

**Comment by jordwalke** [comment]
Here's what will work best:
(You have to make sure it only ever runs in the nerd tree syntax highlighting - not other panes).

    " Replace any `[` or `]` with underscore.
    " We'll hide the underscores anyways.
    syntax match hideBracketsInNerdTree "[\]|\[]*" conceal cchar=_

   " Must be completely hidden otherwise cursorline doesn't highlight the concealed bg color correctly.
   set conceallevel=3
   set concealcursor=nvic

This seems to work great - I just don't know where in the plugin is best to place this.

Also, when concealed, you'll probably want to add one extra space after the icon (can't be done with conceal and has to be done in the plugin) just so it doesn't look as cramped.

**Comment by jordwalke** [comment]
Looks like just placing all that above code in the `NERDTreeWebDevIconsRefreshListener` method works. It also doesn't seem to interfere with other buffers that have conceal since conceal settings seem to be per buffer.

**Comment by ryanoasis** [comment]
:smile: Great sounds like you have probably the best solution. Do you want to submit a PR ? If not I will eventually get to making your changes myself (just might take a little longer that way)

**Comment by jordwalke** [comment]
See my note, it didn't work and I don't understand Vim plugin architecture well enough.

**Comment by ryanoasis** [comment]
Ah okay no problem. What you have given me is good info to make an attempt, so stay tuned :+1:

**Comment by jordwalke** [comment]
:+1:

**Comment by ryanoasis** [comment]
fixed with v0.4.0 release

**Comment by jordwalke** [comment]
:+1:
