### ISSUE TITLE
Setting global options broken (only works from .gvimrc)

### ISSUE THREAD

**Issue by jordwalke** [ryanoasis/vim-webdevicons#28]
`g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['js']`:

I tried setting this at the very end of my `.vimrc` and it didn't work because the global dictionary wasn't set yet. When are we to configure this?

**Comment by ryanoasis** [comment]
I used to test with something like this in my vimrc:

let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['md'] = ''

But maybe it is not currently working so I will test it again soon. Thanks

**Comment by jordwalke** [comment]
I believe it's not working. I tried before loading bundles, and after as well. (I use `Vundle`).

**Comment by ryanoasis** [comment]
Ah okay thanks, I'll try to take a look soon

**Comment by ryanoasis** [comment]
I have a fix coming for this but it involved more changes than I initially thought. This is currently broken and does not work from `vimrc`

If you happen to use gui vim it **is** however working, then you can try setting in `gvimrc`

**Comment by ryanoasis** [comment]
fixed with v0.4.0 release
