### ISSUE TITLE
Console vim glyph defaults to single width and can't set to double.

### ISSUE THREAD

**Issue by AnthonyBobsin** [ryanoasis/vim-webdevicons#31]
I'm using console vim and the glyphs in NERDTree default to single width. I am unable to set it to double width even with confirming WebDevIconsUnicodeGlyphDoubleWidth is set to 1. There is still the empty space before the closing bracket. Not sure if console vim is just unable to have double width or not.

**Comment by ryanoasis** [comment]
It might be the font you are using. Did you set your terminal to the double width glyph variant?

Which font from: https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher ?

**Comment by AnthonyBobsin** [comment]
I am using the Sauce Code one, but I realized I am using the monospaced. That might be restricting the glyphs as well?

**Comment by AnthonyBobsin** [comment]
Just tried the non-monospaced and it works perfectly now, thanks for your help! If you don't mind, I was also curious on how to use the second set of glyphs.

**Comment by ryanoasis** [comment]
Great! No problem :smile: 

Yeah all WebDevIconsUnicodeGlyphDoubleWidth Does right now is tell whether or not to add an extra space for when the font is likely using double width glyphs, it does not adjust the font or anything. I should probably clarify that more in the readme.

Oh the second set: those are just included in the font and I believe I only use a few of them on the plugin currently, but I tried to make it in such a way that you can easily extend or use different glyphs if you don't like the defaults :smile:

**Comment by AnthonyBobsin** [comment]
Sounds great, I will read the docs and look into extending my preferences on glyphs. Thanks again for the help, and I love what you're doing with this repo by the way, excellent job!
