### ISSUE TITLE
g:webdevicons_conceal_nerdtree_brackets

### ISSUE THREAD

**Issue by bdryanovski** [ryanoasis/vim-webdevicons#37]
By setting `g:webdevicons_conceal_nerdtree_brackets` to `1` hide `null` text in all buffers/windows/tabs everywhere.

`let g:webdevicons_conceal_nerdtree_brackets = 1`
![screen shot 2015-04-16 at 10 50 40](https://cloud.githubusercontent.com/assets/204564/7176384/8f02e272-e426-11e4-9ca6-6b1f29f4ea95.png)

`let g:webdevicons_conceal_nerdtree_brackets = 0`
![screen shot 2015-04-16 at 10 51 15](https://cloud.githubusercontent.com/assets/204564/7176383/8f026018-e426-11e4-8a0d-0d5610955a1f.png)

**Comment by ryanoasis** [comment]
Uh oh, thats not good. I will try to look into this today. Thanks and sorry about that :stuck_out_tongue:

**Comment by ryanoasis** [comment]
Hmm I am so far unable to replicate. Looks like `function` is also being affected. My guess is there is another syntax using conceal and there is a conflict or something.

![selection_16_04_15_09 48 35_527x630_001](https://cloud.githubusercontent.com/assets/8083459/7182354/c441ca5a-e41e-11e4-927e-24183cf13b06.png)


I tried debugging my setup with: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

:question: Can you tell me all of the plugins you use ?

:question: Was this in gvim or vim (looks like gvim?) ?

:question: Did you see this without ever opening nerdtree ?

**Comment by bdryanovski** [comment]
Hi,
It's ok I found it by chance.

* You could see my Vim setup here [Github](https://github.com/bdryanovski/vimrc)
* Yep it's gVim on MacOS
* No need to open NerdTree

I will try to debug it a bit later today or tomorrow

For the moment I think that the issue is comming from here:
```vim
exec 'autocmd filetype nerdtree syntax match hideBracketsInNerdTree "[\]|\[]*" contained conceal cchar=_ containedin=ALL'
set conceallevel=3
set concealcursor=nvic
```

**Comment by ryanoasis** [comment]
Ahha! I *do* see it now.

I had to do a plugin update, seems like something has changed on https://github.com/pangloss/vim-javascript

I was actually quite a bit far behind (I had yet to clean-up my contrib branch from vim plugins):
`
[2015-04-16 10:03:12] Plugin pangloss/vim-javascript
[2015-04-16 10:03:12] $ cd '/home/ryan/.vim/bundle/vim-javascript' && git pull && git submodule update --init --recursive
[2015-04-16 10:03:12] > Updating f8122fd..8a409f7
`

Now I am getting the same as you

**Comment by ryanoasis** [comment]
@bdryanovski Yep that is a recent code addition to hide brackets on nerdtree... and for *me* it _was_ working prior to updating my version of `pangloss/vim-javascript`

**Comment by bdryanovski** [comment]
I didn't even notice that `pangloss/vim-javascript` had e updated - nice to know.

**Comment by ryanoasis** [comment]
Oh okay yep.

Well I think I actually have a fix, but I need to do some more testing:
```vim
      exec 'autocmd filetype nerdtree set conceallevel=3'
      exec 'autocmd filetype nerdtree set concealcursor=nvic'
```
