### ISSUE TITLE
Quotes are concealed in json files

### ISSUE THREAD

**Issue by punknroll** [ryanoasis/vim-webdevicons#40]
When I open a .json file with some some quotes are concealed

![conceal](https://cloud.githubusercontent.com/assets/361815/7227220/62b1f812-e74f-11e4-987b-169d0c569e75.png)

You can fix it with this setting
let g:webdevicons_conceal_nerdtree_brackets=0

greetz

**Comment by ryanoasis** [comment]
can you tell me which version you have?

`echo webdevicons#version()`

**Comment by punknroll** [comment]
0.4.0
I installed it via NeoBundle.

**Comment by ryanoasis** [comment]
can you try to update?

this issue should be fixed in 0.4.1

Let me know either way if that solves your problem (without having to disable the conceal feature)

**Comment by punknroll** [comment]
hmm...after :NeoBundleUpdate! I still have version 0.4.0.

**Comment by punknroll** [comment]
I switched to master branch and the issue is gone. Thanx for your help.

**Comment by ryanoasis** [comment]
@punknroll :+1: no problem. Glad that was the fix :smile:
