### ISSUE TITLE
Square brackets are back.

### ISSUE THREAD

**Issue by jordwalke** [ryanoasis/vim-webdevicons#42]
I cannot explain when this happens exactly, but sometimes the square brackets around the icons resurface! Have you noticed this?

**Comment by jordwalke** [comment]
FWIW, I use this plugin - https://github.com/jistr/vim-nerdtree-tabs
I'm not sure if it's relevant, but either way it's a great plugin and you might want to check it out. I know it does do some refreshing across tabs to ensure everything remains in-sync. That could be related to the fact that the square brackets are returning.

**Comment by ryanoasis** [comment]
Thamks I will check that one out and see if there are issues :+1:

**Comment by jordwalke** [comment]
I notice it happens when I open a file from the nerd tree.

**Comment by jordwalke** [comment]
Actually, not just when I open a file from the nerd tree, but when I open some specific file extensions (even with an `:e myFile.extension` command) it makes all the icons have square brackets again!

**Comment by blueyed** [comment]
Can you check if the settings are applied in the NERDTree buffer?
https://github.com/ryanoasis/vim-webdevicons/blob/5f4e194dc628f6bb16a23b64f595a42bf8bcad04/plugin/webdevicons.vim#L186-L192

**Comment by jordwalke** [comment]
Looks like the file type `indent` plugin had the following:

    syntax enable

I don't know why that was causing problems but when I commented it out, it fixed the problem

**Comment by jordwalke** [comment]
Closing but it would be nice to know why this happens.

**Comment by blueyed** [comment]
Which file had it?

**Comment by ryanoasis** [comment]
Nice glad you found a fix but it would be nice to know the exact file to try to fix this.

I was unable to replicate before

**Comment by jordwalke** [comment]
It was in a custom plugin that I was writing.
