### ISSUE TITLE
Broken in newest NerdTree

### ISSUE THREAD

**Issue by nobleach** [ryanoasis/vim-webdevicons#44]
As of the May 1st update to NerdTree, I get this error:
![screenshot 2015-05-01 10 19 30](https://cloud.githubusercontent.com/assets/217134/7433151/aa2fee70-efeb-11e4-923d-e2baa08f8470.png)

**Comment by ryanoasis** [comment]
Hey, this doesn't seem to be a problem with latest nerdtree.

I just replicated this but I had to load webdevicons before nerdtree.

Can you try to move the plugin load of vim-webdevicons to be *after* nerdtree ?

Even if that fixes it I believe I need to adjust that logic that does the feature check if possible

**Comment by nobleach** [comment]
Yep, you are correct. I moved NerdTree up, and it's good to go. Thanks!

**Comment by ryanoasis** [comment]
:+1:  glad that was it. No problem!
