### ISSUE TITLE
Idea for a font-installation script

### ISSUE THREAD

**Issue by wikimatze** [ryanoasis/vim-webdevicons#5]
Hi Ryan,

thanks for this awesome plugin. I installed your plugin and would like to add a script, which installs the `*.otf` font. I got it running under Xubuntu, to change the script for other operating systems should be no problem.

**Comment by wikimatze** [comment]
Any news about this so far?

**Comment by ryanoasis** [comment]
Sorry, yes I was waiting for another response on the https://github.com/ryanoasis/vim-webdevicons/pull/6 comment thread I guess.

I think if you want to make the changes proposed by @blueyed then I will wait else I will at least merge it in as-is so it's at least available and you get the contrib credit :smile:

**Comment by blueyed** [comment]
I think only the documentation should get changed. There is no need for an extra script / indirection.
I've thought that this was agreed upon in #6.
