### ISSUE TITLE
ICON width issue? 

### ISSUE THREAD

**Issue by DemonCloud** [ryanoasis/vim-webdevicons#52]
![bugfix](https://cloud.githubusercontent.com/assets/7436361/7694658/f128439e-fe15-11e4-94df-352e2f30fec3.png)

System   :  Ubuntu Kylin 15.04
Software :  Gvim 7.4
Bundle    :  Vundle
Fonts      :  DejaVu Sans Mono for Powerline Plus Nerd File Types Mono 10

and other font get same issue too~

after I update my Nerdtree plugin.  
may I upload my .vimrc file ?

-- download the picture and rename to [ vimrc ] --
![vimrc copy](https://cloud.githubusercontent.com/assets/7436361/7694712/a86ce94c-fe16-11e4-87e2-06b1ae1c066c.png)

**Comment by ryanoasis** [comment]
Thanks, saw your vimrc. I will check it out.

Whats with the gray highlighting or is that part of the issue?

**Comment by DemonCloud** [comment]
@ryanoasis  

there is  a space between ICON and FILENAME.

The color scheme name is [ hybrid ] .. other themes also make same issue.

**Comment by ryanoasis** [comment]
@DemonCloud I still haven't looked at this yet but for now you could try adjusting this setting:

```vim
let g:WebDevIconsNerdTreeAfterGlyphPadding = ''
```

**Comment by ryanoasis** [comment]
@DemonCloud can you see if this solution fixes your issue: https://github.com/ryanoasis/vim-webdevicons/issues/53#issuecomment-108127414

**Comment by DemonCloud** [comment]
@ryanoasis  Yeah. I get it now

**Comment by ryanoasis** [comment]
@DemonCloud This is pretty much done and fixed just want to do a bit more testing before releasing. If you would like to check this out on [branch 0.4.3](https://github.com/ryanoasis/vim-webdevicons/tree/0.4.3) I would be grateful

**Comment by DemonCloud** [comment]
@ryanoasis 
How I config the vimrc file . I was getting same issue with ``PluginUpdate``

Please see this picture and how do I highlight the gray line
![bug](https://cloud.githubusercontent.com/assets/7436361/8142407/3addc0f8-11ae-11e5-8e85-58724bee4169.png)

**Comment by DemonCloud** [comment]
I fix the Problem with
``autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=AL``
