### ISSUE TITLE
Would you add this 3270 terminal fonts.. Please~

### ISSUE THREAD

**Issue by DemonCloud** [ryanoasis/vim-webdevicons#57]
https://github.com/rbanffy/3270font

you can down loadit~

nice programming fonts~

**Comment by ryanoasis** [comment]
Sure, license looks acceptable to attempt to patch

**Comment by DemonCloud** [comment]
@ryanoasis 
T_T  
I don't know how to patch the font ~

May be only I can introduce the fonts to you...
http://tobiasjung.name/profont/

Really small programming font

**Comment by ryanoasis** [comment]
@DemonCloud I can patch it unless you want to.

Just so you know, to patch: https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher

Both of these you have mentioned seem to have licenses that allow patching so we are good on the legal part looks like

**Comment by ryanoasis** [comment]
@DemonCloud working on patching these fonts and even some more fonts soon after that

**Comment by ryanoasis** [comment]
@DemonCloud give one of these a try: https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher/tree/0.3.0/patched-fonts/3270
:smile:

**Comment by DemonCloud** [comment]
@ryanoasis 

Thank you very much.~

**Comment by ryanoasis** [comment]
@DemonCloud does the patched font work fairly well for you? If so I would like to close this issue

**Comment by DemonCloud** [comment]
@ryanoasis  No , The icon width also has some problem

**Comment by ryanoasis** [comment]
@DemonCloud Okay I may close this issue and open a new one on https://github.com/ryanoasis/font-nerd-icons instead since this issue is related to the font :smile:

**Comment by ryanoasis** [comment]
closing and opened ticket on ryanoasis/font-nerd-icons/issues/15 instead
