### ISSUE TITLE
Can't see directory node icon in NERDTree

### ISSUE THREAD

**Issue by ZzAntares** [ryanoasis/vim-webdevicons#59]
Hello, I've installed vim-webdevicons successfully (I think), but now I can not change the NerdTree symbol, because the one appearing by default is ugly (and it looks is cut):

![screen shot 2015-06-06 at 00 11 41](https://cloud.githubusercontent.com/assets/3653680/8018430/def35abe-0be0-11e5-86e4-4d11f66553f0.png)

I've tried with this settings in my vimrc , but they have no effect:

```
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:WebDevIconsUnicodeDecorateFolderNodeDefaultSymbol = ''

let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['nerdtree'] = ''
```

What I'm doing wrong?

Note: I've patched Monaco font (I'm on MacOSX), other icons are showing well, but directory nodes are not. I'm using gvim.

Thanks for your help.

Note 2: I don't know if could be related but my NERDTree is configured to not launch on gvim start.

**Comment by ryanoasis** [comment]
Thanks there are other reports of glyphs being cut off I will have to look into.

You can try to see if increasing the padding helps:
```vim
let g:WebDevIconsNerdTreeAfterGlyphPadding = '  '
```

As for the folder glyph not showing my suspicion is that I did not add it explicitly to the set of new glyphs but rather I chose the folder glyph arbitrarily from a font but it probably doesn't exist in all (including the one you tried)

**Comment by ZzAntares** [comment]
Hello, adding `let g:WebDevIconsNerdTreeAfterGlyphPadding = '  '` works, but the folder icon is not showing, but I think that's my issue, I patched Monaco font, but the one I was using was Monaco for Powerline (previously patched by me for using with airline), I think I need to patch that new font instead of the original. Later I will try.

Thanks.

**Comment by ryanoasis** [comment]
@ZzAntares , oh okay. Let me know if that works for you. 

The font patcher I made should have put the folder glyph as well so that is odd.

**Comment by ryanoasis** [comment]
@ZzAntares just FYI #72 is probably going to fix this for you. I will get it into the next version

**Comment by ZzAntares** [comment]
Thanks we'll see, as patching the power line font didn't work either.

**Comment by ryanoasis** [comment]
@ZzAntares can you see if pulling latest master fixes this issue for you? Thanks

**Comment by ZzAntares** [comment]
Still not working, even pulled the lastest patcher, patched again and nothing

![screen shot 2015-06-28 at 01 58 07](https://cloud.githubusercontent.com/assets/3653680/8395495/55b7a506-1d39-11e5-8e02-84f07acfea3a.png)

Config in .vimrc:
![screen shot 2015-06-28 at 01 57 43]
(https://cloud.githubusercontent.com/assets/3653680/8395496/55bc1ae6-1d39-11e5-85eb-16bf3517135f.png)

I guess I've to surrender :(

**Comment by ryanoasis** [comment]
@ZzAntares Sorry about this :sob: 

Actually I think the issue is not as confusing as I initially thought. It appears to be `g:WebDevIconsUnicodeDecorateFolderNodes` in users `vimrc` setting is getting overwritten by the plugin :blush: 

To confirm the suspicion you can call `let g:WebDevIconsUnicodeDecorateFolderNodes = 1` after vim has loaded and refresh the nerdtree.

I am going to push a fix soon and let me know if it works for you

**Comment by ryanoasis** [comment]
Please close if this fixes the issue for you :smile:

**Comment by ZzAntares** [comment]
This now works but it does not remove the ugly icon in the very left, what could be happening?

![screen shot 2015-06-28 at 14 20 23](https://cloud.githubusercontent.com/assets/3653680/8397898/f97a0b2c-1da0-11e5-82f9-63ae130b7df1.png)

**Comment by ryanoasis** [comment]
Actually I think those are `NERDTreeDirArrows` 

If you move cursor over the character and enter `ga` you should see the hex and octal value.

Here is how mine looks with and without `NERDTreeDirArrows` set:

![selection_28_06_15_15 44 33_328x370_001](https://cloud.githubusercontent.com/assets/8083459/8397985/5218b466-1dad-11e5-9857-749b465d4dc7.png)

![selection_28_06_15_15 48 40_298x252_001](https://cloud.githubusercontent.com/assets/8083459/8397988/5668f0bc-1dad-11e5-90ec-280f181d9cde.png)

**Comment by ZzAntares** [comment]
you're right those are the nerdtree arrows, but I don't understand why they disappear does the patcher removes the glyphs?

This looks with the `let g:NERDTreeDirArrows=0`:

![screen shot 2015-06-29 at 01 11 47](https://cloud.githubusercontent.com/assets/3653680/8402137/d23ae20e-1dfd-11e5-9d45-47324116d4ad.png)

**Comment by ryanoasis** [comment]
The patcher shouldn't be removing any glyphs but it may be changing the size in a way that causes the terminal not to be able to render them. What terminal are you using?

Can you send me the font you are using? The pre-patched version and the patched version. Thanks.

**Comment by ZzAntares** [comment]
I'm using macvim/gvim, this is the font:

`set guifont=Monaco\ for\ Powerline\ Plus\ Nerd\ File\ Types:h15`

The original font is Monaco, but I've been using "Monaco por powerline" for the symbols, that is the one I patched, patching the original didn't work neither.

**Comment by ryanoasis** [comment]
Try copying and pasting the character into gvim buffer to see if it will even show: `▸`

If you completely disable vim-webdevicons does the `▸` show up?

Do other fonts work fine? E.g. if you even try setting gvim to use another system font does the arrow show?

At least on my system that character mostly is coming from either `DejaVu Sans` or `DejaVu Sans Mono` and not *normally* in any of the patched or un-patched fonts.

I don't see anything wrong with the patched Monaco fonts I have found so far.

**Comment by ZzAntares** [comment]
Hello, copying and pasting the character in the gvim buffer does not show the arrow glyph. And yes using another font even a non-patched the arrows show. I'd like to use the Monaco font, do you have an already patched working font to try?

Thanks.

**Comment by ryanoasis** [comment]
Strange it sounds like a problem with that font. I will try patching it on my end and upload it depending on license

**Comment by ryanoasis** [comment]
Maybe try https://github.com/nicholasc/vim-monaco-webdevicons?

**Comment by ZzAntares** [comment]
Great! It worked like a charm. I suppose then was a problem with my patched font or the patcher.

Thanks for your help, I suppose we can close this (reopen if need it). Thanks!

**Comment by ryanoasis** [comment]
Awesome! Good to hear. :tada: 

I will probably add that font to the list of those included in https://github.com/ryanoasis/font-nerd-icons
