### ISSUE TITLE
Perl support

### ISSUE THREAD

**Issue by zaferot** [ryanoasis/vim-webdevicons#60]
Hi!
Is it possible to support Perl?

**Comment by ryanoasis** [comment]
Yes, good suggestion. It should be very easy since the glyph is already there.

I think I will also add: `rss`, `clojure`, `F#`, `rust`, `D`, `Erlang`, `Vim script`

**Comment by zaferot** [comment]
Great! Thanks!

**Comment by ryanoasis** [comment]
Work in progress preview:
![selection_16_06_15_19 04 52_457x34_001](https://cloud.githubusercontent.com/assets/8083459/8196496/98b1ef52-145a-11e5-8ef5-45ead2d282e5.png)

**Comment by ryanoasis** [comment]
@zaferot this should be working in [0.5.0](https://github.com/ryanoasis/vim-webdevicons/tree/0.5.0) **if** you want to give it an early test :smirk:

**Comment by zaferot** [comment]
Great! But, I'll wait the changes in master :)
Thanks!
