### ISSUE TITLE
Rename project: vim-webdevicons to vim-devicons ?

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/vim-webdevicons#64]
Rename project: vim-webdevicons to vim-devicons ?

Reasoning - icons are not web development specific and this name would now more accurately match the intended scope.

Any thoughts?

Vote: http://poll.gitrun.com/ryanoasis/vim-webdevicons/issues/64

**Comment by hoop33** [comment]
+1

**Comment by adambiggs** [comment]
+1

**Comment by cnicolov** [comment]
+1

**Comment by DemonCloud** [comment]
+1

**Comment by SageEx** [comment]
+1

**Comment by ivan-cukic** [comment]
+1

**Comment by calidion** [comment]
:+1:

**Comment by daedric** [comment]
+1

**Comment by nicholasc** [comment]
+1

**Comment by ijks** [comment]
+1

**Comment by delphinus35** [comment]
+1

**Comment by ryanoasis** [comment]
Closing, will be done in #76 and #77
