### ISSUE TITLE
Unknown function when opening Vim

### ISSUE THREAD

**Issue by majjoha** [ryanoasis/vim-webdevicons#67]
After installing this plugin, I started receiving the following error message when opening Vim:

```
$ vim
Error detected while processing /Users/mathias/.env/.vim/bundle/vim-webdevicons/plugin/webdevicons.vim:
line  256:
E117: Unknown function: airline#add_statusline_func
Press ENTER or type command to continue
```

I use [lightline.vim](https://github.com/itchyny/lightline.vim) rather than vim-airline, so I guess it makes sense that it cannot find the function.

**Comment by ryanoasis** [comment]
It looks like I do not check for that functions existence. Should be an easy fix.

For now, as a work-around, setting this in your `vimrc` should help:

```vim
let g:webdevicons_enable_airline_statusline = 0
```

**Comment by majjoha** [comment]
Cool. It seems to resolve the issue.
