### ISSUE TITLE
Some airline variables are not working

### ISSUE THREAD

**Issue by SageEx** [ryanoasis/vim-webdevicons#69]
I have disabled file encoding information in airline by modifying g:airline_section_y by 
let g:airline_section_y = '%{getcwd()}'
But after installing vim-webdevicons this variable no longer works.
Before 
![screenshot from 2015-06-18 12-12-20](https://cloud.githubusercontent.com/assets/7141867/8225512/4cf54d16-15b3-11e5-8412-703b2552d55e.png)

After installing vim-webdevicons
![screenshot from 2015-06-18 12-09-50](https://cloud.githubusercontent.com/assets/7141867/8225517/6066430a-15b3-11e5-8ae7-05c2b3674edc.png)

The line affecting airline_section_y is not working.

How to get the variables working again ?

**Comment by ryanoasis** [comment]
Can you try setting this in your `vimrc`:
```vim
let g:webdevicons_enable_airline_statusline_fileformat_symbols = 0
```

By default I override that section which maybe isn't the best thing to do.

**Comment by SageEx** [comment]
Thanks, this works.
Thanks a lot for this plugin.

**Comment by ryanoasis** [comment]
@SageEx no problem. Glad that fixed it for you.
