### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by daedric** [ryanoasis/vim-webdevicons#71]
Hi,
I've two small bugs:

* First, when I re-source my vimrc, I've bracket appearing. I'd expect them to appear on startup or not at all. Maybe it is some kind of conflict with the nerdtree-git-plugin but I respected the order:
```
" here because of webdevicons
NeoBundle 'bling/vim-airline'

NeoBundle 'scrooloose/nerdtree'
NeoBundle 'Xuyuanp/nerdtree-git-plugin'
NeoBundle 'jistr/vim-nerdtree-tabs'

NeoBundle 'ryanoasis/vim-webdevicons'
"NeoBundle 'ryanoasis/nerd-filetype-glyphs-fonts-patcher'
```

I've a vim file by type of plugins and I moved vim-airline into the nerdtree.git as well as yours.
Here are some images: before: [before](https://daedric.fr/before.png) and after: [after](http://daedric.fr/after.png)

* second bug is best shown:  [bug2](http://daedric.fr/screenshot.png)

Please let me know what information you need :)

Thanks

**Comment by ryanoasis** [comment]
* per bug 1 - I have confirmed it as well on my end. re-sourcing causes the brackets to appear
* per bug 2 - Not quite sure I see what you think the bug is here? the misalignment due to having both this plugin and git-nerdtree-plugin ? Can you please elaborate?

**Comment by daedric** [comment]
About the second but I've no idea. Could it be that nerdtree-git-plugin uses too wide characters ?
Could it be some padding added by your plugin that should not be added because git-nerdtree-plugin display something itself ?

**Comment by ryanoasis** [comment]
@daedric I dont *think* the second issue is a bug but it could be the default setting isn't good enough.

You can adjust the padding:
```vim
let g:WebDevIconsNerdTreeAfterGlyphPadding = ''
```

Let me know if that helps with the 2nd issue, I might need to look into the default setting for true mono fonts.

As for the **1st** issue I am looking into it.

**Comment by ryanoasis** [comment]
@daedric Okay I think I have something that will *at least* help. 

Can you pull the latest and then add this to your `vimrc` (after any setting of syntax):
```vim
" after a re-source, fix syntax matching issues (concealing brackets):
if exists("webdevicons#refresh")
	call webdevicons#refresh()
endif
```

**Comment by daedric** [comment]
Still no luck ! I added your snippet at the end of my vimrc.
If it helps, I can create a tarball of my vim config so you can test if you're not able to reproduce the problem...

**Comment by daedric** [comment]
BTW, the padding stuff did not really improve. There is still some misalignment issue.

**Comment by ryanoasis** [comment]
@daedric Yes if you could send me your `vimrc` I can try to see if it works for me.

The misalignment I think I will try to add a filler character if the node has a git related flag, hopefully not too hard to do.

**Comment by ryanoasis** [comment]
@daedric For the misalignment how does this look to you:

![selection_29_06_15_16 04 46_294x328_001](https://cloud.githubusercontent.com/assets/8083459/8417425/a1788478-1e7a-11e5-9e44-c63d8bb7fa64.png)

**Comment by daedric** [comment]
Yep.
I prepare a tarball with my vim configuration (it is split in several files)

**Comment by ryanoasis** [comment]
@daedric Okay let me know when and where to download it and I will test out the re-sourcing :+1:

**Comment by daedric** [comment]
http://daedric.fr/vimconf.tgz

**Comment by ryanoasis** [comment]
@daedric Thanks I'll let you know!

**Comment by ryanoasis** [comment]
@daedric can you try this at the bottom instead:

```vim
if exists("g:loaded_webdevicons")
	call webdevicons#refresh()
endif
```

Note: I did try to use your vimrc but I don't use neobundle and had some errors but I did see that the fix I gave you actually was _not_ working for me as well but this version seems to work

**Comment by daedric** [comment]
You should maybe disable YouCompleteMe, it requires a CMake, a c++ compiler, and python development libraries.
I tried your new fix. It does not work for me :(

Thanks for trying !

**Comment by ryanoasis** [comment]
I actually use YouCompleteMe 

What if you call `webdevicons#refresh()` directly after re-sourcing?

**Comment by daedric** [comment]
No luck :(

**Comment by ryanoasis** [comment]
Hmm that should at least do something. Does it open and close nerdtree if it is open (it should at least do that) ?

Do you have any errors in `:messages` after executing?

You are up to date with the lastest code in master?

**Comment by ryanoasis** [comment]
@daedric I am considering closing this for now, I cannot replicate. I added some of the notes to the readme. We can open a new issue if it persists :smile:

**Comment by daedric** [comment]
no problem :) good luck !
