### ISSUE TITLE
Why WebDevIconsGetFileFormatSymbol() returns with &enc?

### ISSUE THREAD

**Issue by delphinus35** [ryanoasis/vim-webdevicons#73]
`&enc` is a setting that decides vim internal encoding. I think `WebDevIconsGetFileFormatSymbol()` should return information of editing files, but not the whole vim setting such as `&enc`.

Probably, it has been mistaken from `&fenc`?

**Comment by ryanoasis** [comment]
@delphinus35 :+1: Yes looks like you are right it should be `fenc` not `enc`. Just checked that in the help and the vim-airline code and `fenc` is what we want here :blush: 

Thanks! I will make sure this gets fixed in the next bug/minor release

**Comment by delphinus35** [comment]
Thx for reply. When I wrote powerline plugin, it seems that I need a different approach for this. Please see #74.

**Comment by ryanoasis** [comment]
@delphinus35 you can remove the encoding from that functions return. See my comment: https://github.com/ryanoasis/vim-webdevicons/pull/74#issuecomment-118615377 :smile:

**Comment by ryanoasis** [comment]
@delphinus35 I have fixed this in [0.5.0](https://github.com/ryanoasis/vim-webdevicons/tree/0.5.0)

**Comment by delphinus35** [comment]
👍
